apiVersion: v1
kind: Service
metadata:
  name: forgerockinterview-service
spec:
  selector:
    app: forgerockinterview-pod
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP